/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class AudioChapterTimecodesInner {
  "end": string;
  "start": string;
  "verseId": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "end",
      baseName: "end",
      type: "string",
      format: "",
    },
    {
      name: "start",
      baseName: "start",
      type: "string",
      format: "",
    },
    {
      name: "verseId",
      baseName: "verseId",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap(): Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> {
    return AudioChapterTimecodesInner.attributeTypeMap;
  }

  public constructor() {}
}
