/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* An **AudioBibleSummary** object is a minimal representation of a single auditory translation (NIV, ESV, etc.) of the Bible, typically attached to an associated **Bible**
*/
export class AudioBibleSummary {
    /**
    * A string  consisting of a 16-digit unique string followed by a _publication number_ (`-01`, `-02`). A few popular examples are:    | Bible                                  | Bible ID              |  | -------------------------------------- | --------------------- |  | New International Version (**NIV**)    | `78a9f6124f344018-01` |  | New American Standard Bible (**NASB**) | `a761ca71e0b3ddcf-01` |  | Christian Standard Bible (**CSB**)     | `a556c5305ee15c3f-01` |
    */
    'id': string;
    /**
    * Name of this Audio Bible version
    */
    'name': string;
    /**
    * Localized name of this Audio Bible version
    */
    'nameLocal': string;
    /**
    * Description of this Audio Bible version
    */
    'description': string;
    /**
    * Localized description of this Audio Bible version
    */
    'descriptionLocal': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLocal",
            "baseName": "nameLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionLocal",
            "baseName": "descriptionLocal",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AudioBibleSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

