/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AudioChapterNext } from '../models/AudioChapterNext.ts';
import { AudioChapterPrevious } from '../models/AudioChapterPrevious.ts';
import { AudioChapterTimecodesInner } from '../models/AudioChapterTimecodesInner.ts';
import { HttpFile } from '../http/http.ts';

/**
* An **Audio Chapter** object represents a single auditory chapter of the Bible. Rather than verses or sections, audio chapter verse content is stored at the chapter level.
*/
export class AudioChapter {
    /**
    * A string consisting of a [Book](https://docs.api.bible/guides/books) ID and a chapter number. A few examples are:    | Chapter       | Chapter ID |  | ------------- | ---------- |  | Genesis 1     | `GEN.1`    |  | John 3        | `JHN.3`    |  | Revelation 22 | `REV.22`   |
    */
    'id': string;
    /**
    * The **Bible ID** this audio chapter is associated with
    */
    'bibleId': string;
    /**
    * The audio chapter number
    */
    'number': string;
    /**
    * The **Book ID** this audio chapter is associated with
    */
    'bookId': string;
    /**
    * A presigned link to the audio file for this audio chapter. This link  will expire, so it is recommended to download that audio file using that link as quickly as you are able. It is **not** recommended  that you stream audio directly from the provided link, as you will run into a number of ongoing issues.
    */
    'resourceUrl': string;
    /**
    * Allows you to match verses in a chapter to a specific time code in the audio file. This can be helpful if you are using both text and audio Bibles and would like to highlight a verse as it is being read.
    */
    'timecodes'?: Array<AudioChapterTimecodesInner>;
    /**
    * The timestamp the presigned `resourceUrl` link will expire
    */
    'expiresAt': number;
    /**
    * The full reference for this audio chapter
    */
    'reference': string;
    'next'?: AudioChapterNext;
    'previous'?: AudioChapterPrevious;
    /**
    * Copyright info for this audio 
    */
    'copyright'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceUrl",
            "baseName": "resourceUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "timecodes",
            "baseName": "timecodes",
            "type": "Array<AudioChapterTimecodesInner>",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "AudioChapterNext",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "AudioChapterPrevious",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AudioChapter.attributeTypeMap;
    }

    public constructor() {
    }
}

