/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AudioBibleSummary } from '../models/AudioBibleSummary.ts';
import { BibleCountriesInner } from '../models/BibleCountriesInner.ts';
import { Language } from '../models/Language.ts';
import { HttpFile } from '../http/http.ts';

/**
* A **Bible** object represents a single translation (NIV, ESV, etc.) of the Bible. 
*/
export class Bible {
    /**
    * A string  consisting of a 16-digit unique string followed by a _publication number_ (`-01`, `-02`). A few popular examples are:    | Bible                                  | Bible ID              |  | -------------------------------------- | --------------------- |  | New International Version (**NIV**)    | `78a9f6124f344018-01` |  | New American Standard Bible (**NASB**) | `a761ca71e0b3ddcf-01` |  | Christian Standard Bible (**CSB**)     | `a556c5305ee15c3f-01` |
    */
    'id': string;
    /**
    * The first 16 digits of the`id` field, represents this Bible\'s ID in the [Digital Bible Library](https://library.bible)
    */
    'dblId': string;
    /**
    * Abbreviation for this Bible version
    */
    'abbreviation': string;
    /**
    * Localized abbreviation for this Bible version
    */
    'abbreviationLocal': string;
    /**
    * Copyright information for this Bible
    */
    'copyright'?: string;
    'language': Language;
    /**
    * Countries this Bible is available in
    */
    'countries': Array<BibleCountriesInner>;
    /**
    * Name of this Bible version
    */
    'name': string;
    /**
    * Localized name for this Bible version
    */
    'nameLocal': string;
    /**
    * Description of this Bible version
    */
    'description': string;
    /**
    * Localized description of this Bible version
    */
    'descriptionLocal': string;
    /**
    * Additional information about this Bible provided by it\'s publisher
    */
    'info'?: string;
    /**
    * The type of Bible
    */
    'type': BibleTypeEnum;
    /**
    * The last time this Bible was updated
    */
    'updatedAt': Date;
    'relatedDbl': string;
    'audioBibles'?: Array<AudioBibleSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "dblId",
            "baseName": "dblId",
            "type": "string",
            "format": ""
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string",
            "format": ""
        },
        {
            "name": "abbreviationLocal",
            "baseName": "abbreviationLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "Language",
            "format": ""
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<BibleCountriesInner>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLocal",
            "baseName": "nameLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionLocal",
            "baseName": "descriptionLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BibleTypeEnum",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "relatedDbl",
            "baseName": "relatedDbl",
            "type": "string",
            "format": ""
        },
        {
            "name": "audioBibles",
            "baseName": "audioBibles",
            "type": "Array<AudioBibleSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Bible.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BibleTypeEnum = "text" | "audio" ;

