/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BibleCountriesInner {
    'id': string;
    'name': string;
    'nameLocal': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLocal",
            "baseName": "nameLocal",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BibleCountriesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

