/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChapterSummary } from '../models/ChapterSummary.ts';
import { HttpFile } from '../http/http.ts';

/**
* A **Book** object represents a single book (Matthew, Mark, etc.) of a single Bible.
*/
export class Book {
    /**
    * A 3-digit code representing the book\'s name. A few examples are:    | Book Name | Book ID |  | --------- | ------- |  | Genesis   | `GEN`   |  | Mark      | `MRK`   |  | 1 John    | `1JN`   |
    */
    'id': string;
    /**
    * The **Bible ID** this book is associated with
    */
    'bibleId': string;
    /**
    * The abbreviation for this book, typically matches this book\'s ID
    */
    'abbreviation': string;
    /**
    * The name of this book
    */
    'name': string;
    /**
    * The extended name of this book, if applicable
    */
    'nameLong': string;
    'chapters'?: Array<ChapterSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLong",
            "baseName": "nameLong",
            "type": "string",
            "format": ""
        },
        {
            "name": "chapters",
            "baseName": "chapters",
            "type": "Array<ChapterSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Book.attributeTypeMap;
    }

    public constructor() {
    }
}

