/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChapterNext } from "../models/ChapterNext.ts";

export class Chapter {
  "id": string;
  "bibleId": string;
  "number": string;
  "bookId": string;
  "content": string;
  "reference": string;
  "verseCount": number;
  "next"?: ChapterNext;
  "previous"?: ChapterNext;
  "copyright": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "",
    },
    {
      name: "bibleId",
      baseName: "bibleId",
      type: "string",
      format: "",
    },
    {
      name: "number",
      baseName: "number",
      type: "string",
      format: "",
    },
    {
      name: "bookId",
      baseName: "bookId",
      type: "string",
      format: "",
    },
    {
      name: "content",
      baseName: "content",
      type: "string",
      format: "",
    },
    {
      name: "reference",
      baseName: "reference",
      type: "string",
      format: "",
    },
    {
      name: "verseCount",
      baseName: "verseCount",
      type: "number",
      format: "",
    },
    {
      name: "next",
      baseName: "next",
      type: "ChapterNext",
      format: "",
    },
    {
      name: "previous",
      baseName: "previous",
      type: "ChapterNext",
      format: "",
    },
    {
      name: "copyright",
      baseName: "copyright",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap(): Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> {
    return Chapter.attributeTypeMap;
  }

  public constructor() {}
}
