/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* A **ChapterSummary** object represents a single chapter of the Bible without verse content.
*/
export class ChapterSummary {
    /**
    * A string consisting of a [Book](https://docs.api.bible/guides/books) ID and a chapter number. A few examples are:    | Chapter       | Chapter ID |  | ------------- | ---------- |  | Genesis 1     | `GEN.1`    |  | John 3        | `JHN.3`    |  | Revelation 22 | `REV.22`   |
    */
    'id': string;
    /**
    * The **Bible ID** this chapter is associated with
    */
    'bibleId': string;
    /**
    * The chapter number
    */
    'number': string;
    /**
    * The **Book ID** this chapter is associated with
    */
    'bookId': string;
    /**
    * The full reference for this chapter
    */
    'reference': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChapterSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

