/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChapterNext } from '../models/ChapterNext.ts';
import { ChapterPrevious } from '../models/ChapterPrevious.ts';
import { HttpFile } from '../http/http.ts';

/**
* A **Chapter** object represents a single chapter of the Bible, including verse content.
*/
export class Chapter {
    /**
    * A string consisting of a [Book](https://docs.api.bible/guides/books) ID and a chapter number. A few examples are:    | Chapter       | Chapter ID |  | ------------- | ---------- |  | Genesis 1     | `GEN.1`    |  | John 3        | `JHN.3`    |  | Revelation 22 | `REV.22`   |
    */
    'id': string;
    /**
    * The **Bible ID** this chapter is associated with
    */
    'bibleId': string;
    /**
    * The chapter number
    */
    'number': string;
    /**
    * The **Book ID** this chapter is associated with
    */
    'bookId': string;
    /**
    * Chapter verse content. Can be formatted as `html`, `json`, or `text`.
    */
    'content': string;
    /**
    * The full reference for this chapter
    */
    'reference': string;
    /**
    * The number of verses in this chapter
    */
    'verseCount': number;
    'next'?: ChapterNext;
    'previous'?: ChapterPrevious;
    /**
    * Copyright info for this chapter
    */
    'copyright': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "verseCount",
            "baseName": "verseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "ChapterNext",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "ChapterPrevious",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Chapter.attributeTypeMap;
    }

    public constructor() {
    }
}

