/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AudioBible } from '../models/AudioBible.ts';
import { HttpFile } from '../http/http.ts';

export class GetAudioBible200Response {
    'data': AudioBible;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AudioBible",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAudioBible200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

