/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Book } from '../models/Book.ts';
import { HttpFile } from '../http/http.ts';

export class GetBook200Response {
    'data': Book;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Book",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBook200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

