/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChapterSummary } from '../models/ChapterSummary.ts';
import { HttpFile } from '../http/http.ts';

export class GetChapters200Response {
    'data': Array<ChapterSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ChapterSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetChapters200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

