/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Chapter } from "../models/Chapter.ts";
import { Meta } from "../models/Meta.ts";

export class GetChapter200Response {
  "data": Chapter;
  "meta": Meta;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "data",
      baseName: "data",
      type: "Chapter",
      format: "",
    },
    {
      name: "meta",
      baseName: "meta",
      type: "Meta",
      format: "",
    },
  ];

  static getAttributeTypeMap(): Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> {
    return GetChapter200Response.attributeTypeMap;
  }

  public constructor() {}
}
