/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Meta } from '../models/Meta.ts';
import { Section } from '../models/Section.ts';
import { HttpFile } from '../http/http.ts';

export class GetSection200Response {
    'data': Section;
    'meta': Meta;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Section",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Meta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetSection200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

