/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Language {
    'id': string;
    'name': string;
    'nameLocal': string;
    'script': string;
    'scriptDirection': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLocal",
            "baseName": "nameLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string",
            "format": ""
        },
        {
            "name": "scriptDirection",
            "baseName": "scriptDirection",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Language.attributeTypeMap;
    }

    public constructor() {
    }
}

