/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Language {
    /**
    * ISO 639-3 three digit language code
    */
    'id': string;
    /**
    * English name of the language
    */
    'name': string;
    /**
    * Localized name of the language
    */
    'nameLocal': string;
    /**
    * The type of script used for this language
    */
    'script': string;
    /**
    * The direction this language writes
    */
    'scriptDirection': LanguageScriptDirectionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameLocal",
            "baseName": "nameLocal",
            "type": "string",
            "format": ""
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string",
            "format": ""
        },
        {
            "name": "scriptDirection",
            "baseName": "scriptDirection",
            "type": "LanguageScriptDirectionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Language.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LanguageScriptDirectionEnum = "LTR" | "RTL" ;

