/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Metadata returned alongside verse content. Primarily used for view tracking.
*/
export class Meta {
    /**
    * A [FUMS Token](https://docs.api.bible/resources/fair-use) to be used in the FUMS system
    */
    'fumsToken': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fumsToken",
            "baseName": "fumsToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Meta.attributeTypeMap;
    }

    public constructor() {
    }
}

