/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Meta {
    'fums': string;
    'fumsId': string;
    'fumsJsInclude': string;
    'fumsJs': string;
    'fumsNoScript': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fums",
            "baseName": "fums",
            "type": "string",
            "format": ""
        },
        {
            "name": "fumsId",
            "baseName": "fumsId",
            "type": "string",
            "format": ""
        },
        {
            "name": "fumsJsInclude",
            "baseName": "fumsJsInclude",
            "type": "string",
            "format": ""
        },
        {
            "name": "fumsJs",
            "baseName": "fumsJs",
            "type": "string",
            "format": ""
        },
        {
            "name": "fumsNoScript",
            "baseName": "fumsNoScript",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Meta.attributeTypeMap;
    }

    public constructor() {
    }
}

