/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* A **Passage** object represents an arbitrary range of verses from the Bible. These ranges are not predefined values, but instead depend on the given input, known as a **Passage ID**.
*/
export class Passage {
    /**
    * Consists of two [Verse](https://docs.api.bible/guides/verses) IDs separated by a `-`. These  **Verse IDs** can span chapters and books, though passages are limited to 200 verses.  A few passage examples are:    | Verse Range                             | Passage ID          |  | --------------------------------------- | ------------------- |  | Genesis 1:1 - Genesis 2:3               | `GEN.1.1-GEN.2.3`   |  | John 3:1 - John 3:16                    | `JHN.3:1-JHN.3.16`  |  | 1 Corinthians 16:1 - 2 Corinthians 1:23 | `1CO.16.1-2CO.1.23` |
    */
    'id': string;
    /**
    * The **Bible ID** this passage is associated with
    */
    'bibleId': string;
    /**
    * The ID assigned to this passage by it\'s publishing organization, typically not relevant.
    */
    'orgId': string;
    /**
    * Passage verse content, truncated to the first 200 verses. Can be formatted as `html`, `json`, or `text`.
    */
    'content': string;
    /**
    * The full reference for this passage
    */
    'reference': string;
    /**
    * The number of verses in this passage.     If it equals `200`, your requested passage was likely truncated. To fetch the full passage you will need to split it into smaller sub-passages and try again.
    */
    'verseCount': number;
    /**
    * Copyright info for this passage
    */
    'copyright': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "verseCount",
            "baseName": "verseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Passage.attributeTypeMap;
    }

    public constructor() {
    }
}

