/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class SearchResponseVersesInner {
    /**
    * A string consisting of a [Book](https://docs.api.bible/guides/books) ID, a chapter number, and a verse number. A few examples are:    | Verse           | Verse ID   |  | --------------- | ---------- |  | Genesis 1:1     | `GEN.1.1`  |  | John 3:16       | `JHN.3.16` |  | Revelation 21.4 | `REV.21.4` |
    */
    'id': string;
    /**
    * The ID assigned to this verse by it\'s publishing organization, typically not relevant.
    */
    'orgId': string;
    /**
    * The **Bible ID** this verse is associated with
    */
    'bibleId': string;
    /**
    * The **Book ID** this verse is associated with
    */
    'bookId': string;
    /**
    * The **Chapter ID** this verse is associated with
    */
    'chapterId': string;
    /**
    * The full reference for this verse
    */
    'reference': string;
    /**
    * Verse content, formatted as `text`. Additional information about this verse can be fetched by making a request to `/bibles/{bibleId}/verses/{verseId}`
    */
    'text': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "chapterId",
            "baseName": "chapterId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponseVersesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

