/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Passage } from '../models/Passage.ts';
import { SearchResponseVersesInner } from '../models/SearchResponseVersesInner.ts';
import { HttpFile } from '../http/http.ts';

/**
* The result of executing a search query. Paginated using the `limit` and `offset` query parameters.
*/
export class SearchResponse {
    /**
    * The initial search\'s `query` parameter
    */
    'query': string;
    /**
    * The initial search\'s `limit` parameter
    */
    'limit': number;
    /**
    * The original search\'s `offset` parameter
    */
    'offset': number;
    /**
    * The total number of search results
    */
    'total': number;
    /**
    * The number of verses returned
    */
    'verseCount': number;
    /**
    * The verses that match the search `query`. If a passage was searched rather than keywords, this array will be empty.
    */
    'verses': Array<SearchResponseVersesInner>;
    'passages'?: Array<Passage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "verseCount",
            "baseName": "verseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "verses",
            "baseName": "verses",
            "type": "Array<SearchResponseVersesInner>",
            "format": ""
        },
        {
            "name": "passages",
            "baseName": "passages",
            "type": "Array<Passage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

