/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Passage } from '../models/Passage.ts';
import { SearchVerse } from '../models/SearchVerse.ts';
import { HttpFile } from '../http/http.ts';

export class SearchResponse {
    'query': string;
    'limit': number;
    'offset': number;
    'total': number;
    'verseCount': number;
    'verses': Array<SearchVerse>;
    'passages'?: Array<Passage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "verseCount",
            "baseName": "verseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "verses",
            "baseName": "verses",
            "type": "Array<SearchVerse>",
            "format": ""
        },
        {
            "name": "passages",
            "baseName": "passages",
            "type": "Array<Passage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

