/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

export class SectionSummary {
  "id": string;
  "bibleId": string;
  "bookId": string;
  "title": string;
  "firstVerseId": string;
  "lastVerseId": string;
  "firstVerseOrgId": string;
  "lastVerseOrgId": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "",
    },
    {
      name: "bibleId",
      baseName: "bibleId",
      type: "string",
      format: "",
    },
    {
      name: "bookId",
      baseName: "bookId",
      type: "string",
      format: "",
    },
    {
      name: "title",
      baseName: "title",
      type: "string",
      format: "",
    },
    {
      name: "firstVerseId",
      baseName: "firstVerseId",
      type: "string",
      format: "",
    },
    {
      name: "lastVerseId",
      baseName: "lastVerseId",
      type: "string",
      format: "",
    },
    {
      name: "firstVerseOrgId",
      baseName: "firstVerseOrgId",
      type: "string",
      format: "",
    },
    {
      name: "lastVerseOrgId",
      baseName: "lastVerseOrgId",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap(): Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> {
    return SectionSummary.attributeTypeMap;
  }

  public constructor() {}
}
