/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* A **SectionSummary** object represents a known range of verses in the Bible, typically tied to a story, without verse content. Not every Bible has sections enabled. For Bibles with sections enabled, sections are sequential and _should_ cover nearly every verse if queried in order.
*/
export class SectionSummary {
    /**
    * A string consisting of a [Book](https://docs.api.bible/guides/books) ID and a section number. A few examples from the book of Genesis are:    | Section Title | Verse Range                | Section ID |  | ------------- | -------------------------- | ---------- |  | The Beginning | Genesis 1:1 - Genesis 2:3  | `GEN.S1`   |  | Adam and Eve  | Genesis 2:4 - Genesis 2:25 | `GEN.S2`   |  | The Fall      | Genesis 3:1 - Genesis 3:24 | `GEN.S3`   |
    */
    'id': string;
    /**
    * The **Bible ID** this section is associated with
    */
    'bibleId': string;
    /**
    * The **Bible ID** this section is associated with
    */
    'bookId': string;
    /**
    * The title of this section
    */
    'title': string;
    /**
    * The `id` of the first verse in this section
    */
    'firstVerseId': string;
    /**
    * The `id` of the last verse in this section
    */
    'lastVerseId': string;
    /**
    * The `orgId` of the last verse in this section. Typically not relevant
    */
    'firstVerseOrgId': string;
    /**
    * The `orgId` of the last verse in this section, typically not relevant.
    */
    'lastVerseOrgId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstVerseId",
            "baseName": "firstVerseId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastVerseId",
            "baseName": "lastVerseId",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstVerseOrgId",
            "baseName": "firstVerseOrgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastVerseOrgId",
            "baseName": "lastVerseOrgId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SectionSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

