/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SectionNext } from "../models/SectionNext.ts";
import { HttpFile } from "../http/http.ts";

export class Section {
  "id": string;
  "bibleId": string;
  "bookId": string;
  "chapterId": string;
  "title": string;
  "content": string;
  "verseCount": number;
  "firstVerseId": string;
  "lastVerseId": string;
  "firstVerseOrgId": string;
  "lastVerseOrgId": string;
  "copyright": string;
  "next"?: SectionNext;
  "previous"?: SectionNext;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "",
    },
    {
      name: "bibleId",
      baseName: "bibleId",
      type: "string",
      format: "",
    },
    {
      name: "bookId",
      baseName: "bookId",
      type: "string",
      format: "",
    },
    {
      name: "chapterId",
      baseName: "chapterId",
      type: "string",
      format: "",
    },
    {
      name: "title",
      baseName: "title",
      type: "string",
      format: "",
    },
    {
      name: "content",
      baseName: "content",
      type: "string",
      format: "",
    },
    {
      name: "verseCount",
      baseName: "verseCount",
      type: "number",
      format: "",
    },
    {
      name: "firstVerseId",
      baseName: "firstVerseId",
      type: "string",
      format: "",
    },
    {
      name: "lastVerseId",
      baseName: "lastVerseId",
      type: "string",
      format: "",
    },
    {
      name: "firstVerseOrgId",
      baseName: "firstVerseOrgId",
      type: "string",
      format: "",
    },
    {
      name: "lastVerseOrgId",
      baseName: "lastVerseOrgId",
      type: "string",
      format: "",
    },
    {
      name: "copyright",
      baseName: "copyright",
      type: "string",
      format: "",
    },
    {
      name: "next",
      baseName: "next",
      type: "SectionNext",
      format: "",
    },
    {
      name: "previous",
      baseName: "previous",
      type: "SectionNext",
      format: "",
    },
  ];

  static getAttributeTypeMap(): Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> {
    return Section.attributeTypeMap;
  }

  public constructor() {}
}
