/**
 * API.Bible
 * Rest API Documentation for API.Bible.
 *
 * OpenAPI spec version: 1.6.3
 * Contact: support@api.bible
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Information about the previous **Chapter**, if one exists. Can be used to navigate the Bible backwards one chapter at a time.
*/
export class VersePrevious {
    /**
    * The next verse\'s `id`
    */
    'id': string;
    /**
    * The previous verse\'s `bookId`
    */
    'bookId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VersePrevious.attributeTypeMap;
    }

    public constructor() {
    }
}

