/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VerseNext } from '../models/VerseNext.ts';
import { HttpFile } from '../http/http.ts';

export class Verse {
    'id': string;
    'orgId': string;
    'bibleId': string;
    'bookId': string;
    'chapterId': string;
    'content': string;
    'reference': string;
    'verseCount': number;
    'copyright': string;
    'next'?: VerseNext;
    'previous'?: VerseNext;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bibleId",
            "baseName": "bibleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookId",
            "baseName": "bookId",
            "type": "string",
            "format": ""
        },
        {
            "name": "chapterId",
            "baseName": "chapterId",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "verseCount",
            "baseName": "verseCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "VerseNext",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "VerseNext",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Verse.attributeTypeMap;
    }

    public constructor() {
    }
}

